(define-library (foo)
  (import (vanity core))
  (define-constant puts (##foreign.function "C" "int puts(const char *)"))
  (define-constant fabs (##foreign.function "C" "double fabs(double)"))
  (define stop-the-warn #f)
  #;(puts "Hello, world!")
  #;(puts "Hayo")
  (unless (= (fabs 3) 3)
    (exit 1))
  (unless (equal? (map fabs '(1 2 -7)) '(1.0 2.0 7.0))
    (exit 1)))
(import (foo))
(import (vanity core))
(unless (= 3((##intrinsic "VBitwiseIor" 3) 1 2))
  (exit 1))
(unless (eq? #\A ((##basic-intrinsic "VIntChar" 1) 65))
  (exit 1))
(unless (procedure? (##basic-intrinsic "VIntChar" 1))
  (exit 1))
