(define-library (foo)
  (import (vanity core))
  (export lmao lmao2)
  (define (lmao x)
    (let ((foo (lambda (x) (* 2 x))))
      (foo (foo x))))
  (define (lmao2 x)
    (define (foo x) (+ x 1))
    (foo (foo x)))
)
(import (vanity core) (foo))
(displayln (lmao 6))
(displayln (lmao2 2))
