(import (vanity core))

(define failures 0)
(define (check name got want)
  (unless (equal? got want)
    (set! failures (+ failures 1))
    (printf "FAIL ~A: got ~S want ~S\n" name got want)))

(define (collect for-each-proc . seqs)
  (let ((acc '()))
    (apply for-each-proc (lambda xs (set! acc (cons xs acc))) seqs)
    (reverse acc)))

(check "string-for-each empty" (collect string-for-each "") '())
(check "string-for-each 1" (collect string-for-each "abc") '((#\a) (#\b) (#\c)))
(check "string-for-each 2" (collect string-for-each "abc" "xy") '((#\a #\x) (#\b #\y)))
(check "string-for-each 3" (collect string-for-each "abc" "xyz" "12") '((#\a #\x #\1) (#\b #\y #\2)))
(check "string-for-each 4" (collect string-for-each "ab" "xyz" "123" "pqr") '((#\a #\x #\1 #\p) (#\b #\y #\2 #\q)))

(check "string-map empty" (string-map char-upcase "") "")
(check "string-map 1" (string-map char-upcase "abc") "ABC")
(check "string-map 2" (string-map (lambda (a b) b) "abc" "xy") "xy")
(check "string-map 3" (string-map (lambda (a b c) c) "abc" "xyz" "12") "12")
(check "string-map 4" (string-map (lambda (a b c d) d) "abc" "xyz" "123" "pq") "pq")
(check "string-upcase" (string-upcase "Hello, World") "HELLO, WORLD")

(check "vector-for-each 1" (collect vector-for-each #(1 2 3)) '((1) (2) (3)))
(check "vector-for-each 2" (collect vector-for-each #(1 2 3) #(4 5)) '((1 4) (2 5)))
(check "vector-for-each 4" (collect vector-for-each #(1 2) #(3 4) #(5 6) #(7 8 9)) '((1 3 5 7) (2 4 6 8)))
(check "vector-map 1" (vector-map (lambda (x) (* x x)) #(1 2 3)) #(1 4 9))
(check "vector-map 3" (vector-map + #(1 2 3) #(10 20 30) #(100 200)) #(111 222))
(check "vector-map 4" (vector-map + #(1 2) #(10 20) #(100 200) #(1000 2000 3000)) #(1111 2222))
(check "vector->list" (vector->list #(1 2 3)) '(1 2 3))

(define (check-typevector name from-list to-list copy)
  (let ((v (from-list '(1 2 3 4 5))))
    (check (sprintf "~A->list" name) (to-list v) (to-list (from-list '(1 2 3 4 5))))
    (check (sprintf "~A->list length" name) (length (to-list v)) 5)
    (check (sprintf "~A-copy" name) (to-list (copy v)) (to-list v))
    (check (sprintf "~A-copy start" name) (to-list (copy v 2)) (cddr (to-list v)))
    (check (sprintf "~A-copy start end" name) (to-list (copy v 1 3)) (list (cadr (to-list v)) (caddr (to-list v))))
    (check (sprintf "~A equal?" name) (equal? v (copy v)) #t)
    (check (sprintf "~A not equal?" name) (equal? v (copy v 1)) #f)
    (check (sprintf "~A not equal? same length" name) (equal? v (from-list '(1 2 3 4 6))) #f)))

(check-typevector "f32vector" (lambda (xs) (list->f32vector (map inexact xs))) f32vector->list f32vector-copy)
(check-typevector "f64vector" (lambda (xs) (list->f64vector (map inexact xs))) f64vector->list f64vector-copy)
(check-typevector "s32vector" list->s32vector s32vector->list s32vector-copy)
(check-typevector "u16vector" list->u16vector u16vector->list u16vector-copy)
(check-typevector "s16vector" list->s16vector s16vector->list s16vector-copy)
(check-typevector "u8vector" list->u8vector u8vector->list u8vector-copy)
(check-typevector "s8vector" list->s8vector s8vector->list s8vector-copy)
(check "s32vector->list values" (s32vector->list (list->s32vector '(-1 0 7))) '(-1 0 7))
(check "vector equal?" (equal? #(1 (2) "x") (vector 1 (list 2) "x")) #t)
(check "vector not equal?" (equal? #(1 2) #(1 3)) #f)

(exit (= failures 0))
