(import (vanity waybill) (vanity core))
(define (assert-equal? x y)
  (unless (equal? x y)
    (printf "~S is not equal to ~S~N" x y)
    (exit 1)))
(define (tp-key tp)
  (define-values (broken? key datum) (waybill-unpack tp))
  key)
(define (assert-ephemeron-equals eph broken? key datum)
  (define-values (eph-broken? eph-key eph-datum) (waybill-unpack eph))
  (unless
    (and (equal? broken? eph-broken?)
         (equal? key eph-key)
         (equal? datum eph-datum))
    (printf "ephemeron not equal #ephemeron(~A ~A ~A): ~A ~A ~A" eph-broken? eph-key eph-datum broken? key datum)
    (exit 1)))

(define tg (make-clearinghouse))
(define-values (tp0 tp1) (let ((tp (make-strong-transport-waybill tg (cons 1 1) (cons #t #t) (list 'x)))) (values tp (make-strong-transport-waybill tg (cons 2 2) 666))))
(##vcore.garbage-collect #f)
(define tp (let ((tp (make-strong-transport-waybill tg (cons 3 3) #f 555))) tp))
(##vcore.garbage-collect #t)
(define keys
  (list
    (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing))
    (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing))))
(assert-equal? (waybill-signaled? tp0) #t)
(assert-ephemeron-equals tp0 #f (cons 1 1) (cons #t #t))
(assert-equal? (waybill-address tp0) (list 'x))
(assert-equal? (waybill-signaled? tp1) #t)
(assert-ephemeron-equals tp1 #f (cons 2 2) #f)
(assert-equal? (waybill-address tp1) 666)
(assert-equal? (assoc 1 keys) (cons 1 1))
(assert-equal? (assoc 2 keys) (cons 2 2))
(assert-equal? (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing)) (cons 3 3))
(assert-equal? (clearinghouse-poll! tg) #f)
(define eternal-tp (make-strong-transport-waybill tg 'x #t 999))
(define orphaned-tp  (make-strong-transport-waybill #f (cons #f #f) 'x 888))
(define eternal-orphaned-tp  (make-strong-transport-waybill #f 'y 'x 888))
(##vcore.garbage-collect #t)
(assert-equal? (clearinghouse-poll! tg) #f)
(assert-equal? (waybill-signaled? eternal-tp) #f)
(assert-equal? (waybill-signaled? orphaned-tp) #t)
(assert-equal? (waybill-signaled? eternal-orphaned-tp) #f)

(define tpx (make-strong-transport-waybill tg (cons 'x 'x) '?))
(##vcore.garbage-collect #f)
(define-values (key te) (let ((key (cons 'e 'e))) (values key (make-ephemeral-transport-waybill tg key key '!))))
(##vcore.garbage-collect #f)
(define tpz (make-strong-transport-waybill tg (cons 'z 'z) '?))
(##vcore.garbage-collect #f)
(assert-equal? (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing)) (cons 'x 'x))
(assert-equal? (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing)) (cons 'e 'e))
(assert-equal? (let ((tp (clearinghouse-poll! tg))) (if tp (tp-key tp) 'nothing)) (cons 'z 'z))
(assert-equal? (waybill-address te) '!)
(set! key #f)
(##vcore.garbage-collect #t)
(assert-ephemeron-equals te #t #f #f)
