(define-library (vanity newprint)
  (export printout-list printout-quotation printout-pair printout-vector printout-hash-table printout-record printout-procedure printout
          printout-shared-datum printout-shared
  )
  (import (vanity core))
  (define datum-label-index 0)
  (define (reset-datum-label-index!) (set! datum-label-index 0))
  (define (next-datum-label-index!)
    (let ((i datum-label-index))
      (set! datum-label-index (+ i 1))
      i))

  (define (hash-table-ref/default ht key default)
    (hash-table-ref ht key (lambda () default)))

  ;; first pass: walk x and populate a table mapping object -> refcount
  ;; we only care about objects that can form cycles: pairs, vectors, records, hash-tables
  (define (count-refs! x table)
    (cond
      ((pair? x)
       (let ((count (hash-table-ref/default table x 0)))
         (hash-table-set! table x (+ count 1))
         (when (= count 0)
           (count-refs! (car x) table)
           (count-refs! (cdr x) table))))
      ((vector? x)
       (let ((count (hash-table-ref/default table x 0)))
         (hash-table-set! table x (+ count 1))
         (when (= count 0)
           (let loop ((i 0))
             (when (< i (vector-length x))
               (count-refs! (vector-ref x i) table)
               (loop (+ i 1)))))))
      ((hash-table? x)
       (let ((count (hash-table-ref/default table x 0)))
         (hash-table-set! table x (+ count 1))
         (when (= count 0)
           (count-refs! (hash-table->alist x) table))))
      ((record? x)
       (let ((count (hash-table-ref/default table x 0)))
         (hash-table-set! table x (+ count 1))
         (when (= count 0)
           (let loop ((i 0))
             (when (< i (record-length x))
               (count-refs! (record-ref x i) table)
               (loop (+ i 1)))))))
      (else #f)))

  ;; second pass: print, emitting #N= on first visit to a shared object, #N# on subsequent visits
  ;; table maps object -> refcount (>1 means shared) or label (a fixnum, meaning already printed once)
  (define (printout-shared-impl x write? port table)
    (define (printout-sharing x)
      (let ((info (hash-table-ref/default table x #f)))
        (cond
          ;; not shared at all, just print directly
          ((or (not info) (eq? info 1))
           (printout-shared-datum x write? port table))
          ;; already labeled: emit #N#
          ((pair? info)
           (##vcore.display-word "#" port)
           (##vcore.display-word (cdr info) port)
           (##vcore.display-word "#" port))
          ;; shared but not yet labeled: assign a label, emit #N=, recurse to print body
          (else
           (let ((label (next-datum-label-index!)))
             (hash-table-set! table x (cons 'label label))
             (##vcore.display-word "#" port)
             (##vcore.display-word label port)
             (##vcore.display-word "=" port)
             (printout-shared-datum x write? port table)))
          )))
    (printout-sharing x))

  (define (printout-shared-datum x write? port table)
    (cond
      ((pair? x) (printout-shared-list x write? port table))
      ((vector? x) (printout-shared-vector x write? port table))
      ((hash-table? x) (printout-shared-hash-table x write? port table))
      ((record? x) (printout-shared-record x write? port table))
      ((procedure? x) (printout-procedure x write? port 1))
      (write? (##vcore.write x port))
      (else (##vcore.display-word x port))))

  (define (printout-shared-list x write? port table)
    (define (printout-shared-element x)
      (printout-shared-impl x write? port table))
    (##vcore.display-word "(" port)
    (printout-shared-element (car x))
    (let loop ((xs (cdr x)))
      (let ((info (hash-table-ref/default table xs #f)))
        (cond
          ;; xs is a shared/labeled object: print as improper tail
          ((and info (not (eq? info 1)))
           (##vcore.display-word " . " port)
           (printout-shared-element xs))
          ((pair? xs)
           (##vcore.display-word " " port)
           (printout-shared-element (car xs))
           (loop (cdr xs)))
          ((null? xs) #f)
          (else
           (##vcore.display-word " . " port)
           (printout-shared-element xs)))))
    (##vcore.display-word ")" port))

  (define (printout-shared-vector x write? port table)
    (let ((len (vector-length x)))
      (##vcore.display-word "#(" port)
      (let loop ((i 0))
        (when (< i len)
          (when (> i 0) (##vcore.display-word " " port))
          (printout-shared-impl (vector-ref x i) write? port table)
          (loop (+ i 1))))
      (##vcore.display-word ")" port)))

  (define (printout-shared-hash-table x write? port table)
    (let ((eq (hash-table-equivalence-function x)))
      (cond ((eq? eq eq?) (##vcore.display-word "#hasheq" port))
            ((eq? eq eqv?) (##vcore.display-word "#hasheqv" port))
            (else (##vcore.display-word "#hash" port))))
    (printout-shared-impl (hash-table->alist x) write? port table))

  (define (printout-shared-record x write? port table)
    (if (pair? (record-ref x 0))
        (printout-shared-record-nice x write? port table)
        (printout-shared-record-notnice x write? port table)))

  (define (printout-shared-record-notnice x write? port table)
    (##vcore.display-word "#record(" port)
    (printout-shared-impl (record-ref x 0) write? port table)
    (let loop ((i 1))
      (when (< i (record-length x))
        (##vcore.display-word " " port)
        (printout-shared-impl (record-ref x i) write? port table)
        (loop (+ i 1))))
    (##vcore.display-word ")" port))

  (define (printout-shared-record-nice x write? port table)
    (define refl (record-ref x 0))
    (##vcore.display-word "#record(" port)
    (printout-shared-impl (car refl) write? port table)
    (let loop ((i 1) (rest (cdr refl)))
      (when (< i (record-length x))
        (##vcore.display-word " " port)
        (printout-shared-impl (cons (car rest) (record-ref x i)) write? port table)
        (loop (+ i 1) (cdr rest))))
    (##vcore.display-word ")" port))

  (define (printout-shared x write? port)
    (let ((table (make-hash-table eq?)))
      (count-refs! x table)
      (printout-shared-impl x write? port table)))

  (define (printout-shared-tail xs write? port)
    (let ((table (make-hash-table eq?)))
      (count-refs! xs table)
      (printout-shared-tail-impl xs write? port table)))

  (define (printout-shared-tail-impl xs write? port table)
    (let ((info (hash-table-ref/default table xs #f)))
      (cond
        ((and info (not (eq? info 1)))
         (##vcore.display-word " . " port)
         (printout-shared-impl xs write? port table))
        ((pair? xs)
         (##vcore.display-word " " port)
         (printout-shared-impl (car xs) write? port table)
         (printout-shared-tail-impl (cdr xs) write? port table))
        ((null? xs) 'ok)
        (else
         (##vcore.display-word " . " port)
         (printout-shared-impl xs write? port table)))))

  (define (printout-list x write? port fuel)
    (##vcore.display-word "(" port)
    (let* ((fuel (printout (car x) write? port fuel))
           (fuel (let loop ((xs (cdr x)) (fuel fuel))
                   (cond ((pair? xs)
                          (if (<= fuel 0)
                              (begin
                                (printout-shared-tail xs write? port)
                                0)
                              (begin
                                (##vcore.display-word " " port)
                                (loop (cdr xs) (printout (car xs) write? port fuel)))))
                         ((null? xs) fuel)
                         (else
                          (##vcore.display-word " . " port)
                          (printout xs write? port fuel))))))
      (##vcore.display-word ")" port)
      fuel))
  (define (printout-quotation x write? port fuel)
    (##vcore.display-word (cdr (assv (car x) '((quote . "'") (quasiquote . "`") (unquote . ",") (unquote-splicing . ",@")))) port)
    (printout (cadr x) write? port fuel))
  (define (printout-pair x write? port fuel)
    (if (and (memq (car x) '(quote quasiquote unquote unquote-splicing))
             (pair? (cdr x))
             (null? (cddr x)))
        (printout-quotation x write? port fuel)
        (printout-list x write? port fuel)))
  (define (printout-vector x write? port fuel)
    (let ((len (vector-length x)))
      (##vcore.display-word "#(" port)
      (let ((fuel (let loop ((i 0) (fuel fuel))
                    (if (eq? i len)
                        fuel
                        (begin
                          (if (eq? i 0)
                              #f
                              (##vcore.display-word " " port))
                          (loop (+ i 1) (printout (vector-ref x i) write? port fuel)))))))
        (##vcore.display-word ")" port)
        fuel)))
  (define (printout-hash-table x write? port fuel)
    (let ((eq (hash-table-equivalence-function x)))
         (cond ((eq? eq eq?) (##vcore.display-word "#hasheq" port))
               ((eq? eq eqv?) (##vcore.display-word "#hasheqv" port))
               (else (##vcore.display-word "#hash" port))))
    (printout (hash-table->alist x) write? port fuel))
  (define (printout-record-notnice x write? port fuel)
    (##vcore.display-word "#record" port)
    (##vcore.display-word "(" port)
    (let* ((fuel (printout (record-ref x 0) write? port fuel))
           (fuel (let loop ((i 1) (fuel fuel))
                   (if (= i (record-length x))
                       fuel
                       (begin
                         (##vcore.display-word " " port)
                         (loop (+ i 1) (printout (record-ref x i) write? port fuel)))))))
      (##vcore.display-word ")" port)
      fuel))
  (define (printout-record-nice x write? port fuel)
    (define refl (record-ref x 0))
    (##vcore.display-word "#record" port)
    (##vcore.display-word "(" port)
    (let* ((fuel (printout (car refl) write? port fuel))
           (fuel (let loop ((i 1) (rest (cdr refl)) (fuel fuel))
                   (if (= i (record-length x))
                       fuel
                       (begin
                         (##vcore.display-word " " port)
                         (let ((fuel (printout (cons (car rest) (record-ref x i)) write? port fuel)))
                           (loop (+ i 1) (cdr rest) fuel)))))))
      (##vcore.display-word ")" port)
      fuel))
  (define (printout-record x write? port fuel)
    (if (pair? (record-ref x 0))
        (printout-record-nice x write? port fuel)
        (printout-record-notnice x write? port fuel)))
  (define (printout-procedure x write? port fuel)
    (##vcore.display-word "#closure" port)
    ;(let ((info ((##basic-intrinsic "VGetProcDebugInfo" 1) x)))
    (let ((info ((##intrinsic "VGetProcDebugInfo" 2 2) x)))
      (if info (printout (car info) write? port fuel) fuel)))
  (define (printout x write? port fuel)
    (if (<= fuel 0)
        (begin (printout-shared x write? port) 0)
        (let ((fuel (- fuel 1)))
          (cond
            ((pair? x) (printout-pair x write? port fuel))
            ((vector? x) (printout-vector x write? port fuel))
            ((hash-table? x) (printout-hash-table x write? port fuel))
            ((record? x) (printout-record x write? port fuel))
            ((procedure? x) (printout-procedure x write? port fuel))
            (write? (##vcore.write x port) fuel)
            (else (##vcore.display-word x port) fuel)))))
)
