(import (vanity core) (vanity list))

#;(let* ((foo (##vcore.async (lambda () (displayln "hayo from the async dimension") (list 'awaited-foo))))
       (bar (##vcore.async (lambda () (displayln "lol") (list 'awaited-bar)))))
  (displayln "doin work")
  (displayln (##vcore.await bar))
  #;(displayln (##vcore.await foo))
  #;(displayln (##vcore.await foo)))
(define (fiber-thunk)
  (let* ((foo (async (lambda () (displayln "hayo from the async dimension") (list 'awaited-foo))))
         (bar (async (lambda () (displayln "lol") (list 'awaited-bar)))))
    (displayln "doin work")
    (displayln (await foo))
    (displayln (await bar))
    (displayln (await foo))
    (displayln (await foo)))
  'fiber-thunk)
(displayln (fiber-fork fiber-thunk))
(displayln "phew, finish!")
