(define-library (caselambda)
  (import (vanity core))
  (export foo bar uwu)
  (define uwu (case-lambda ((x) (* 11 x))))
  (define foo
    (case-lambda (() 0) ((x) 1) ((x y) 2)))
  (define (bar x) (foo 1 x)))
(import (vanity core) (caselambda))
(displayln (foo))
(displayln (foo 1))
(displayln (foo 2 3))
(displayln (uwu (bar 99)))
