(define i 0)
((lambda (x) (x x))
 (lambda (x)
   (##vcore.display-stdout "l00p! ")
   (##vcore.display-stdout i)
   (##vcore.newline-stdout)
   (set! i (##vcore.+ i 1))
   (##vcore.yield-to-host)
   (x x)))
