(##sys.display-word "Hello, World!" (##sys.stdout->port))
(##sys.newline (##sys.stdout->port))

#;(define-library (acker)
  (export ack)
  (define (ack m n)
    (cond ((##sys.eq? m 0) (##sys.+ n 1))
          ((##sys.eq? n 0) (ack (##sys.- m 1) 1))
          (else (ack (##sys.- m 1) (ack m (##sys.- n 1)))))))
#;(import (acker))
(define (ack m n)
    (cond ((##sys.eq? m 0) (##sys.+ n 1))
          ((##sys.eq? n 0) (ack (##sys.- m 1) 1))
          (else (ack (##sys.- m 1) (ack m (##sys.- n 1))))))
(##sys.display-word (ack 3 9) (##sys.stdout->port))
(##sys.newline (##sys.stdout->port))
