include Makefile.sources

vpath %.h src $(INCLUDES)
vpath %.scmh build/include $(INCLUDES)

RUNTIME_STRAP = $(shell find bootstrap/runtime/ -type f -not -name '*.h')
COMPILER_STRAP = $(shell find bootstrap/src/ -type f -not -name '*.h')

VSCHEME = libvscheme.so.$(MAJOR)
VSC = vsc-$(MAJOR)

include config.mk

BOOT_DIR ?= build/boot

BOOT_RUNTIME_OBJ := $(patsubst bootstrap/%, $(BOOT_DIR)/obj/%.o, $(basename $(RUNTIME_STRAP)))
BOOT_COMPILER_OBJ := $(patsubst bootstrap/%, $(BOOT_DIR)/obj/%.o, $(basename $(COMPILER_STRAP)))

.PHONY : hatch boot

$(BOOT_DIR)/obj/%.o : bootstrap/%.c
	@mkdir -p $(dir $@)
	gcc -c $< -o $@ $(CFLAGS) -Ivendor/include -Ibootstrap/include -fPIC -Wno-missing-braces

$(BOOT_DIR)/obj/%.o : bootstrap/%.S
	@mkdir -p $(dir $@)
	gcc -c $< -o $@ $(CFLAGS) -Ivendor/include -Ibootstrap/include -fPIC

$(BOOT_DIR)/lib/libvscheme.so : $(BOOT_RUNTIME_OBJ)
	@mkdir -p $(dir $@)
	gcc -rdynamic -o $@ $^ $(LIBS) $(CFLAGS) -fPIC -shared -Wno-missing-braces -masm=intel

$(BOOT_DIR)/bin/vsc : $(BOOT_COMPILER_OBJ) $(BOOT_DIR)/lib/libvscheme.so
	@mkdir -p $(dir $@)
	gcc -rdynamic -o $@ $(BOOT_COMPILER_OBJ) $(CFLAGS) -L$(BOOT_DIR)/lib -Lvendor/lib -lvscheme -Wl,--no-as-needed -Wno-missing-braces

# Build the bootstrap compiler & runtime without touching INSTALL_DIR.
boot : $(BOOT_DIR)/bin/vsc

hatch : boot
	cp -u vendor/lib/libdfile.so $(INSTALL_DIR)/lib/.
	ldconfig
	ln -sf "$(INSTALL_DIR)/lib/$(VSCHEME)" $(INSTALL_DIR)/lib/libvscheme.so
	ln -sf "$(INSTALL_DIR)/bin/vsc-$(MAJOR)" $(INSTALL_DIR)/bin/vsc
	cp -ar bootstrap/include/* $(INSTALL_DIR)/include/
	cp -a $(BOOT_DIR)/lib/libvscheme.so $(INSTALL_DIR)/lib/$(VSCHEME)
	ldconfig
	cp -a $(BOOT_DIR)/bin/vsc $(INSTALL_DIR)/bin/$(VSC)
