# Run preflight_quick if you are confident you don't need to exercise build from bootstrap
# and preflight otherwise. You generally only need to build from bootstrap if you change
# data representation, or you edit the API of standard library procedures the compiler depends on
include Makefile.sources
include config.mk

.PHONY : preflight preflight_boot preflight_stage1 preflight_stage2 preflight_tests preflight_quick preflight_clean

STAGE0 := preflight/stage0

FARM_LINKS := src runtime include vendor test misc bootstrap resources \
              Makefile Makefile.all Makefile.headers Makefile.sources Makefile.bootstrap config.mk

define farm_setup
@mkdir -p $(1)/config/vanity/compiler
@for l in $(FARM_LINKS); do ln -sfn $(CURDIR)/$$l $(1)/$$l; done
@{ echo '(define-library (vanity compiler config)' ; \
   echo '  (export install-root version platform)' ; \
   echo "  (define version '($(MAJOR) $(MINOR)))" ; \
   echo '  (define install-root "$(CURDIR)/$(1)/")' ; \
   echo "  (define platform 'linux))" ; \
 } > $(1)/config/vanity/compiler/config.scm.tmp
@if cmp -s $(1)/config/vanity/compiler/config.scm.tmp $(1)/config/vanity/compiler/config.scm ; then \
   rm $(1)/config/vanity/compiler/config.scm.tmp ; \
 else \
   mv $(1)/config/vanity/compiler/config.scm.tmp $(1)/config/vanity/compiler/config.scm ; \
 fi
endef

# $(call stage_build,stagedir,prev_stage_dir,targets)
define stage_build
$(call farm_setup,$(1))
LD_LIBRARY_PATH=$(CURDIR)/$(2)/lib:$(CURDIR)/vendor/lib:$$LD_LIBRARY_PATH \
  $(MAKE) -C $(1) $(3) --no-print-directory --no-builtin-rules \
    VSC=$(CURDIR)/$(2)/bin/vsc VSC_DEP=$(CURDIR)/$(2)/bin/vsc
endef

preflight : preflight_tests

preflight_boot :
	@$(MAKE) boot -f Makefile.bootstrap BOOT_DIR=$(STAGE0) --no-print-directory --no-builtin-rules

preflight_stage1 : preflight_boot
	$(call stage_build,preflight/stage1,$(STAGE0),all)

preflight_stage2 : preflight_stage1
	$(call stage_build,preflight/stage2,preflight/stage1,all)

preflight_tests : preflight_stage2
	$(call stage_build,preflight/stage2,preflight/stage1,tests_linux)

preflight_quick :
	@$(MAKE) compiler runtime --no-print-directory --no-builtin-rules
	$(call stage_build,preflight/quick,.,tests)

preflight_clean :
	rm -rf preflight
