; reimport unloads a library and imports it again, rerunning its body.
(define-library (hy reload)
  (import (vanity core))
  (export v)
  (define v (vector 0)))
(define-library (hy reload2)
  (import (vanity core))
  (export w)
  (define w (vector 0)))
(import (vanity core) (vanity assert) (hy reload) (hy reload2))
(define old-v v)
(define old-w w)
(vector-set! v 0 1)
(reimport)
(reimport (hy reload) (hy reload2))
(assert-equal old-v #(1))
(assert-equal v #(0))
(assert-equal (eq? old-v v) #f)
(assert-equal (eq? old-w w) #f)
